apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        command: ["python", "-m", "src.streaming.consumer"]
        image: 284938186002.dkr.ecr.us-east-1.amazonaws.com/credit-risk-engine-consumer:latest
        imagePullPolicy: Always
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: KAFKA_TOPIC_CDS
          value: market-data-cds
        - name: KAFKA_TOPIC_BONDS
          value: market-data-bonds
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: DATABASE_URL
          value: postgresql+psycopg://postgres:postgres@postgres/credit_risk